FROM python:3.13.2

WORKDIR /app

COPY . .

RUN pip3 install -r requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health 

ENTRYPOINT ["streamlit", "run", "streamlit_app.py", "--serverport=8501", "--serveradress=0.0.0.0"]